### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by GreenGitHuber** [allentran/pca-magic#5]
`Traceback (most recent call last):
  File "/Users/jiangqy/Code/ppca/bin/test.py", line 5, in <module>
    from ppca import PPCA
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ppca/__init__.py", line 1, in <module>
    from _ppca import PPCA
ImportError: No module named '_ppca'`

I use Python3

**Comment by GreenGitHuber** [comment]
If I want to use Python3 ,how can I do?

**Comment by allentran** [comment]
Let me take a look, I thought I made it Python 3 compatible.

Probably a relative import type bug I made somewhere
